//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_reservation_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedTicket
    {
        public int BookingId { get; set; }
        public Nullable<int> TrainId { get; set; }
        public string trainame { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> totalfare { get; set; }
        public string @class { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int NumberOfTickets { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual User User { get; set; }
    }
}
