//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_reservation_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancelticket
    {
        public int cancelid { get; set; }
        public Nullable<int> bookid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> trainno { get; set; }
        public Nullable<int> refund_amt { get; set; }
        public Nullable<int> no_of_tickets { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
